"""Generate the public API inventory from ``super_harness.__all__``.

Emits one markdown document per locale so the Docusaurus i18n tree stays
synchronized:

- website/docs/generated-api.md                     (zh-CN, default locale)
- website/i18n/en/docusaurus-plugin-content-docs/current/generated-api.md (en)
"""

from __future__ import annotations

import inspect
from pathlib import Path
from typing import Any

import super_harness

_LOCALES: dict[str, dict[str, Any]] = {
    "zh-CN": {
        "title": "生成的公共 API",
        "intro": "本清单由包的显式 `__all__` 接口自动生成。",
        "kinds": {"class": "类", "function": "函数", "value": "值"},
    },
    "en": {
        "title": "Generated Public API",
        "intro": "This inventory is generated from the package's explicit `__all__` surface.",
        "kinds": {"class": "class", "function": "function", "value": "value"},
    },
}


def render(locale: str) -> str:
    labels = _LOCALES[locale]
    title = str(labels["title"])
    intro = str(labels["intro"])
    kinds = dict(labels["kinds"])
    lines: list[str] = [
        "---",
        f"title: {title}",
        "---",
        "",
        "<!-- Generated by tools/generate_api_reference.py; do not edit manually. -->",
        "",
        intro,
        "",
    ]
    for name in sorted(super_harness.__all__):
        value = getattr(super_harness, name)
        kind = "class" if inspect.isclass(value) else "function" if callable(value) else "value"
        module = getattr(value, "__module__", "builtins")
        lines.extend(
            (
                f"## `{name}`",
                "",
                f"- Kind: `{kinds[kind]}`",
                f"- Module: `{module}`",
                "",
            )
        )
    return "\n".join(lines)


def main() -> None:
    root = Path(__file__).parents[1] / "website"
    destinations = {
        "zh-CN": root / "docs" / "generated-api.md",
        "en": root
        / "i18n"
        / "en"
        / "docusaurus-plugin-content-docs"
        / "current"
        / "generated-api.md",
    }
    for locale, destination in destinations.items():
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(render(locale), encoding="utf-8", newline="\n")
        print(f"wrote {destination}")


if __name__ == "__main__":
    main()
