"""Generate the public API inventory from ``super_harness.__all__``."""

from __future__ import annotations

import inspect
from collections.abc import Callable
from html import escape
from pathlib import Path
from typing import cast

import super_harness


def _signature(value: object) -> str:
    try:
        return str(inspect.signature(cast(Callable[..., object], value)))
    except (TypeError, ValueError):
        return ""


def render() -> str:
    lines = [
        "---",
        "title: Generated Public API",
        "---",
        "",
        "<!-- Generated by tools/generate_api_reference.py; do not edit manually. -->",
        "",
        "This inventory is generated from the package's explicit `__all__` surface.",
        "",
    ]
    for name in sorted(super_harness.__all__):
        value = getattr(super_harness, name)
        kind = "class" if inspect.isclass(value) else "function" if callable(value) else "value"
        signature = escape(_signature(value)) if callable(value) else ""
        summary = escape((inspect.getdoc(value) or "No public docstring.").splitlines()[0])
        signature_line = f"- Signature: `{name}{signature}`" if signature else "- Signature: n/a"
        lines.extend((f"## `{name}`", "", f"- Kind: `{kind}`", signature_line, f"- {summary}", ""))
    return "\n".join(lines)


def main() -> None:
    destination = Path(__file__).parents[1] / "website" / "docs" / "generated-api.md"
    destination.write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    main()
