"""Generate the public API inventory from ``super_harness.__all__``."""

from __future__ import annotations

import inspect
from pathlib import Path

import super_harness


def render() -> str:
    lines = [
        "---",
        "title: Generated Public API",
        "---",
        "",
        "<!-- Generated by tools/generate_api_reference.py; do not edit manually. -->",
        "",
        "This inventory is generated from the package's explicit `__all__` surface.",
        "",
    ]
    for name in sorted(super_harness.__all__):
        value = getattr(super_harness, name)
        kind = "class" if inspect.isclass(value) else "function" if callable(value) else "value"
        module = getattr(value, "__module__", "builtins")
        lines.extend((f"## `{name}`", "", f"- Kind: `{kind}`", f"- Module: `{module}`", ""))
    return "\n".join(lines)


def main() -> None:
    destination = Path(__file__).parents[1] / "website" / "docs" / "generated-api.md"
    destination.write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    main()
