// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    "intro",
    "get-started",
    {
      type: "autogenerated",
      dirName: "guide", // label from guide/_category_.json (localized per locale)
    },
    {
      type: "autogenerated",
      dirName: "internals", // label from internals/_category_.json (localized per locale)
    },
    "examples",
    "api-reference",
    "generated-api",
    "ecosystem",
    "compatibility",
    "troubleshooting",
  ],
};

module.exports = sidebars;